import os
import re
import subprocess
import sys
import shutil
from datetime import datetime

# --- Configuration (UPDATE THESE VALUES) ---
# NOTE: Ensure the user/password/port match your Docker Compose setup.

SOURCE_DB_URL = "postgresql://airflow:airflow@db1:5432/db1" 
TARGET_DB_URL = "postgresql://airflow:airflow@db2:5432/db2"

MIGRATION_DIR = "src/main/resources/db/migration/db2"
TARGET_PROFILE = "db2-local"

# Windows/Linux TimeZone fix for JVM/Maven (Use Asia/Kolkata for IST)
MAVEN_OPTS_FIX = "-Duser.timezone=Asia/Kolkata"

# --- Utility Functions ---

def get_next_version(migration_dir):
    """Calculates the next sequential Flyway version."""
    if not os.path.exists(migration_dir):
        return 1
    
    files = os.listdir(migration_dir)
    versions = []
    # Find all V<number>__*.sql files and extract the number
    for f in files:
        match = re.match(r'V(\d+)__.*\.sql$', f)
        if match:
            versions.append(int(match.group(1)))
    
    return max(versions) + 1 if versions else 1

def delete_generated_file(file_path):
    """Safely deletes the generated migration file."""
    if os.path.exists(file_path):
        try:
            os.remove(file_path)
            print(f"🗑️ Successfully deleted failed migration file: {os.path.basename(file_path)}")
        except OSError as e:
            print(f"⚠️ Warning: Could not delete file {os.path.basename(file_path)}. Please delete manually: {e}")

# --- Core Logic Functions ---

def run_migra_and_generate_script():
    """Compares the schemas using Migra and generates the Flyway SQL file."""
    
    print("=" * 50)
    print(f"Starting Schema Diff: {SOURCE_DB_URL.split('/')[-1]} -> {TARGET_DB_URL.split('/')[-1]}")
    print("=" * 50)
    
    # 1. Run Migra to get the diff SQL
    try:
        print("Running Migra to compare schemas...")

        # Find the absolute path to the migra executable script
        MIGRA_PATH = shutil.which('migra')
        if not MIGRA_PATH:
            raise FileNotFoundError("'migra' executable not found in PATH.")
        
        os.environ['MAVEN_OPTS'] = MAVEN_OPTS_FIX

        migra_command = [MIGRA_PATH, '--unsafe', TARGET_DB_URL, SOURCE_DB_URL]
        
        result = subprocess.run(
            migra_command, 
            stdout=subprocess.PIPE,  # Capture stdout
            stderr=subprocess.STDOUT, # Merge stderr (UserWarning) into stdout
            text=True, 
            # check=True is removed
        )
        
        # The result.stdout now contains both regular output and the warning lines.
        output_lines = result.stdout.splitlines()
        
        # Filter lines that do NOT contain the UserWarning text
        diff_lines = []
        for line in output_lines:
            # ignore for diagnostic/warning indicators
            if 'UserWarning:' in line or 'pkg_resources' in line or 'schemainspect' in line:
                continue
            
            diff_lines.append(line)
        
        diff_sql = '\n'.join(diff_lines).strip()
        
    except FileNotFoundError as e:
        print(f"❌ ERROR: {e}. Check if 'migra' is in your system's PATH.")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print("❌ ERROR: Migra failed unexpectedly.")
        print("--- Subprocess Error (stderr) ---")
        print(e.stderr) 
        sys.exit(1)
    
    # 2. Check for changes
    if not diff_sql:
        print("✅ No schema changes detected. Exiting.")
        return None

    # 3. Generate Flyway Script details
    next_version = get_next_version(MIGRATION_DIR)
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M")
    file_name = f"V{next_version}__{timestamp_str}_schema_sync.sql"
    full_path = os.path.join(MIGRATION_DIR, file_name)

    print(f"Schema changes found. Generating script: {full_path}")

    # 4. Write the captured SQL to the new file
    os.makedirs(MIGRATION_DIR, exist_ok=True)
    with open(full_path, 'w') as f:
        f.write(f"-- Auto-generated by Migra on {os.path.basename(sys.executable)} at {os.getcwd()}\n")
        f.write(diff_sql)
        f.write("\n-- DDL synchronization complete.")
    
    print("-----------------------------------------------------")
    print("Generated SQL Script Contents:")
    print('\n'.join(diff_sql.splitlines()[:5]) + '...')
    print("-----------------------------------------------------")
    
    return full_path

def run_flyway_migration(script_path):
    """Runs the Maven Flyway migrate command with the necessary environment fix."""
    
    # Set the MAVEN_OPTS environment variable for the subprocess
    os.environ['MAVEN_OPTS'] = MAVEN_OPTS_FIX
    
    print(f"\nRunning Flyway migration on profile '{TARGET_PROFILE}'...")
    
    # Command to run: mvn clean compile flyway:migrate -Pdb2-local
    # We use a single string command for reliability with shell=True on Windows
    maven_command = f"mvn clean compile flyway:migrate -P{TARGET_PROFILE}"
    
    try:
        # Execute the Maven command
        subprocess.run(
            maven_command, 
            check=True, 
            text=True, 
            stdout=sys.stdout, 
            stderr=sys.stderr,
            shell=True 
        )
        print("\n✅ Flyway migration completed successfully.")
        return True
    except subprocess.CalledProcessError as e:
        print("\n❌ Flyway migration FAILED.")
        delete_generated_file(script_path)
        print("--- stderr Error : ")
        print(e.stderr) 
        return False
    finally:
        # Clear the environment variable after execution (good practice)
        del os.environ['MAVEN_OPTS']


if __name__ == "__main__":
    generated_file = run_migra_and_generate_script()
    
    if generated_file is not None :
        print("🤖 Automation Mode: Executing migration without user confirmation.")
        
        success = run_flyway_migration(generated_file)
        
        if success:
            print("\n✨ END OF PIPELINE: Schema synchronization successful!")
        else:
            print("\n❌ END OF PIPELINE: Schema synchronization failed during Flyway run.")
            sys.exit(1) 
    else:
        print("\n✅ END OF PIPELINE: No changes to apply.")